// Generated by CoffeeScript 1.7.1
(function() {
  var Canvas, root;

  Canvas = (function() {
    function Canvas(canvasID) {
      this.canvasID = canvasID != null ? canvasID : "canvas";
      this.width = 600;
      this.height = 400;
      this.canvas;
      this.cxt;
    }

    Canvas.prototype.init = function() {
      return this.setCanvas(this.canvasID);
    };

    Canvas.prototype.setCanvas = function(canvasID) {
      this.canvas = window.document.getElementById(canvasID);
      return this.cxt = this.canvas.getContext("2d");
    };

    return Canvas;

  })();

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.Canvas = Canvas;

}).call(this);

//# sourceMappingURL=canvas2.map
