// Generated by CoffeeScript 1.7.1
(function() {
  var canvas;

  canvas = new Canvas;

  canvas.setStrokeStyle("blue").setFillStyle(null).setStrokeWidth(1).line(100, 100, 200, 200);

}).call(this);

//# sourceMappingURL=painter2.map
