// Generated by CoffeeScript 1.7.1
(function() {
  var canvas;

  canvas = new Canvas;

  canvas.setStrokeStyle("lightblue").drawBackgroundGrid(10, 10).setStrokeStyle("black").drawCanvasBorder();

}).call(this);

//# sourceMappingURL=painter2.map
