// Generated by CoffeeScript 1.7.1
(function() {
  var canvas;

  canvas = new Canvas;

  canvas.setStrokeStyle("blue").setFillStyle(null).setStrokeWidth(1).poly(0, 0, 100, 100, 200, 300);

}).call(this);

//# sourceMappingURL=painter2.map
